### PR TITLE
Set executor of CompletableFuture for response with no content.

### LINKED ISSUE #4539: Context is not properly propagated when using helidon-jersey-connector
## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 11
* OS: Windows 11

----------

## Problem Description
When using the "io.helidon.jersey:helidon-jersey-connector", Context is not properly propagated in all scenarios. 
It happens when calling an API that returns 204 (No content) result from a RestClient returning CompletionStage\<Void\>.

## Steps to reproduce
Test project: 
[project.zip](https://github.com/oracle/helidon/files/9109108/project.zip)

1. Run "mvn package". Test fails.
2. Remove the "io.helidon.jersey:helidon-jersey-connector" package and sees that is works.

### PR DESCRIPTION
**Pull request by MadsBrun**
Fixes #4539

### CODE REVIEW

**Comment by MadsBrun** [comment]
@romain-grecourt 
It should already be signed and approved.

**Review by tomas-langer — APPROVED** [review]
LGTM

**Comment by romain-grecourt** [comment]
There was some odd pipeline issues, so I went ahead and merged the master in your branch. I will merge this PR as soon the pipelines pass.

**Pull request merged**
