### PR TITLE
Updating RequestAdapterMp.path to return correct path.

### PR DESCRIPTION
**Pull request by bvkrish83**
Updating RequestAdapterMp.path to return correct path.

To fix issue mentioned in #4406

### CODE REVIEW

**Comment by tjquinno** [comment]
@bvkrish83

**Comment by tjquinno** [comment]
@bvkrish83 

1. The system seems to think you have not completed the contributor agreement. Have you?
2. If you want to complete the agreement and then merge this PR, please add a test that triggers the error without the fix and passes with the fix.
3. We will also need a PR with the same fix and test based on the `helidon-2.x` branch.

Instead, if you prefer, I can create new PRs with the fix and test. Let me know how you want to proceed.

Thanks.

**Comment by bvkrish83** [comment]
@tjquinno

I have started the process on Contributor Agreement, but it is taking more time than expected to get this completed and done.

I am fine with either of the approaches. With the fact that OCA is taking more time than expected, it might be better for you  (or someone else in Helidon Team) take the ownership of this change and get it done.

**Comment by tjquinno** [comment]
@bvkrish83 It's unfortunate the OCA process is not faster, because naturally we welcome and encourage contributions.

That said, I will get to work on PRs myself to fix this in 2.x and 3.x as that might be faster.

**Comment by tjquinno** [comment]
Closing this. See PRs #4434 (2.x) and #4435 (3.x) for the change and added tests.

**Pull request closed without merging**
