### PR TITLE
Create Helidon MP 2.2 bundle

### LINKED ISSUE #764: Add bundle for MP 2.2
We need a bundle for the Helidon MP content for MP 2.2.

### PR DESCRIPTION
**Pull request by tjquinno**
I'm referencing only the OpenAPI-related dependency to the new MP 2.2 bundle (as well as depending on its predecessor 1.2 bundle).

Note that developers do _not_ compile against the Helidon MP OpenAPI code, so it is declared in the bundle with `runtime` scope and it does _not_ appear in the new bundle's `module-info.java`.

This PR also updates the Helidon MP OpenAPI example to use the new bundle and removes the earlier explicit dependency on the Helidon MP OpenAPI artifact (because it's now in the bundle).

Resolves #764

### CODE REVIEW

**Comment by tomas-langer** [comment]
Please also add the dependency to bom/pom.xml

**Comment by tjquinno** [comment]
@tomas-langer Do you mean somewhere in addition to here? https://github.com/oracle/helidon/blob/master/bom/pom.xml#L472-L482

**Comment by tomas-langer** [comment]
There is a section with microprofile bundles in there already, just add it after 1.2

**Comment by tjquinno** [comment]
Oh, you meant to add a dependency for the 2.2 bundle itself, not for the new MP OpenAPI module, to the bom. Got it and done.

**Comment by tjquinno** [comment]
@tomas-langer My commit and push last Friday added the 2.2 bundle to the bom. If that's not what you meant, please  clarify. If it _is_ what you meant, please approve the PR or describe any other concerns you have.

**Pull request merged**
