### PR TITLE
Helidon Features

### LINKED ISSUE #1215: Add support for Helidon Features
We should print out features enabled for the current instance.
This should differ for Helidon SE and MP, only printing out features of the current flavor.

Features are (sample list):
- Server
- JAX-RS
- Config
- Tracing
- Metrics
- Security

Consider support for nesting, example:
- Tracing
  - Jaeger
- Security
  - OIDC
  - ABAC

### PR DESCRIPTION
**Pull request by tomas-langer**
Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

Resolves #1215 

You can control what is printed using configuration option:
`features.print-details`

In SE, this must be on the Config node you present to `ServerConfiguration`, for MP, this must be in the root of configuration.

Default output (`print-details=false`), MP:
~~2019.12.17 19:45:09 INFO io.helidon.common.HelidonFeatures Thread[main,5,main]: Helidon MP 2.0 features: [Config, Fault Tolerance, Health, JWT-Auth, Metrics, OpenAPI, Security, Server, Tracing~~

new:
`2019.12.17 22:54:09 INFO io.helidon.common.HelidonFeatures Thread[main,5,main]: Helidon MP 2.0-SNAPSHOT features: [Config, Fault Tolerance, Health, Metrics, OpenAPI, Security, Server, Tracing]`

Detailed output, MP (updated):
```
2019.12.17 19:45:09 INFO io.helidon.common.HelidonFeatures Thread[main,5,main]: Detailed feature tree:
Config
  Encryption
  YAML
Fault Tolerance
Health
Metrics
OpenAPI
Security
  Authorization
    ABAC
      Policy
      Role
      Scope
      Time
  Integration
    Jersey
  MP
    JWT-Auth
Server
Tracing
  Integration
    Jersey
  Jaeger
```

### CODE REVIEW

**Comment by spericas** [comment]
Shouldn't JWT-Auth be under Security?

**Comment by tomas-langer** [comment]
> Shouldn't JWT-Auth be under Security?

I put it on top level as it is a standalone MP spec. You are most likely right. I will change it after rebasing

**Comment by tomas-langer** [comment]
Rebased on MP revamp

**Comment by tomas-langer** [comment]
Validated with `native-image`

**Pull request merged**
