### PR TITLE
Jackson 2.10.0

### PR DESCRIPTION
**Pull request by barchetta**
Upgrade Jackson to 2.10.0. This should reduce the stream of CVE patches. For more details see 

 https://medium.com/@cowtowncoder/jackson-2-10-features-cd880674d8a2

### CODE REVIEW

**Comment by barchetta** [comment]
Hmmm...I've seen what looks to be a webserver crash both in my pipeline and now on my local machine with this change. Investigating...

**Comment by barchetta** [comment]
I've reproduced a failure locally:
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TSFBuilder
        at io.smallrye.openapi.runtime.io.OpenApiSerializer.serialize(OpenApiSerializer.java:106)
        at io.helidon.openapi.OpenAPISupport.formatDocument(OpenAPISupport.java:224)
```
Looks like this class might not exist in 2.10.

**Comment by ljnelson** [comment]
Hmm, no, `TSFBuilder` exists only in 2.10 and later (see http://fasterxml.github.io/jackson-core/javadoc/2.10/com/fasterxml/jackson/core/TSFBuilder.html).

**Comment by barchetta** [comment]
OK, the problem is `microprofile/tests/tck/tck-opentracing` forces some jackson dependencies to 2.9.0 so we end up with a blend of 2.9.0 and 2.10.0 on the classpath.

**Pull request merged**
