### PR TITLE
Jersey version bump to 3.0.4

### PR DESCRIPTION
**Pull request by Verdent**
Jersey version bump to 3.0.4
Rest client 3.0

### CODE REVIEW

**Review by tomas-langer — DISMISSED** [review]
LGTM

**Review by barchetta — APPROVED** [review]

**Review by tomas-langer — APPROVED** [review]
LGTM

**Review by tomas-langer — APPROVED** [review]
LGTM

**Comment by barchetta** [comment]
Also bumps version of Jackson. See #3879

**Comment by Verdent** [comment]
Relates to #2639

**Pull request merged**
