### PR TITLE
removing unused import

### PR DESCRIPTION
**Pull request by sergioescala**

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@sergioescala You will to sign the OCA for us to accept your contribution. See https://www.oracle.com/technetwork/community/oca-486395.html

**Comment by romain-grecourt** [comment]
The pipeline error should be cleared with this commit: 7f03f9e7af4f108f1114427d04927e74621e7358
Could you refresh your branch (merge/rebase with latest master) to see if it clears out ?
Thanks.

@tjquinno FYI

**Comment by sergioescala** [comment]
Hey @romain-grecourt thanks for the comments, I’ll do what you suggested as soon as possible! Thanks!

**Comment by delabassee** [comment]
@sergioescala I don't see your OCA, let me know if you have any issue.

**Comment by sergioescala** [comment]
Hey @delabassee and @romain-grecourt,

First of all, sorry for the delay, I was doing some personal stuff during this time and I was offline because of that,

About the OCA, I was reading the link and I found that the only way to sign it is by downloading the pdf and send it back to the email posted in there, is that correct? there is another way to do it without downloading the pdf?

Regards,
Sergio

**Comment by romain-grecourt** [comment]
I don't think there is another way, I'll let @delabassee confirm that.

**Comment by romain-grecourt** [comment]
Closing this PR, feel free to re-open when you have completed the OCA process.

**Pull request closed without merging**
