### PR TITLE
Helidon to OKE Guide

### PR DESCRIPTION
**Pull request by mickeyboxell**
Pushing Helidon applications to the Oracle Registry Service and deploying to Oracle Container Engine for Kubernetes.

fixes #424

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@kumar-dhanagopal Can you review this please ?

**Comment by kumar-dhanagopal** [comment]
Sure, by when do you need the review to be completed? If there's no hard deadline, I'll start later this week.

**Comment by romain-grecourt** [comment]
Do it at your convenience.

**Comment by kumar-dhanagopal** [comment]
Sure, I'll start on Thursday.

For now, I scanned the doc to get an idea of the flow. A couple of issues stood out:

- Federated users can now generate auth tokens, if SCIM-propagation is enabled for the federation. The "native user only" constraint isn't applicable anymore.

- When describing <region-code>, let's just provide an example (say, "phx") and then point users to the OCI docs for the full list of regions. If we list all the regions in our doc, then as new regions come up, the doc will need to be updated. E.g., there's now an OCI region in Toronto as well. So the list is already outdated.

**Comment by mickeyboxell** [comment]
Thanks very much for the cursory feedback. @kumar-dhanagopal should I make those updates (federated users and region list) myself or are you planning to do so?

**Comment by kumar-dhanagopal** [comment]
> should I make those updates (federated users and region list) myself or are you planning to do so?

I can make these changes (and other edits as I review the doc), if you're ok with that.

**Comment by mickeyboxell** [comment]
Perfect! Please do.

**Comment by romain-grecourt** [comment]
@kumar-dhanagopal You cannot update this PR because it's located in a branch in Mickey's fork. The only way would be to file a PR against the fork ; the easiest is to have Mickey make the changes.

**Comment by kumar-dhanagopal** [comment]
>  The only way would be to file a PR against the fork
That is what I plan to do.

**Comment by romain-grecourt** [comment]
@kumar-dhanagopal Did you complete the review ?

**Comment by kumar-dhanagopal** [comment]
Not yet @romain-grecourt . I'll let you & @mickeyboxell know when I'm done.

**Comment by kumar-dhanagopal** [comment]
@mickeyboxell - I'm editing the doc offline and have a question about this instruction in your draft: 

>Navigate to the Registry (OCIR) tab and choose the region to which you would like to push the image.

By Registry "tab", did you mean the Registry page in the OCI web console? What's the purpose of that step. I don't see any further instruction in the doc that uses the console. For example, we don't have a step to create a repo in the registry. So I'm not sure why we need the above instruction. Please clarify.

**Comment by mickeyboxell** [comment]
It could be removed or moved to later in the doc. Going to the registry part of the console is supposed to be used to validate that the image push worked.

**Comment by kumar-dhanagopal** [comment]
Got it. I'll be done with my edits today. I'll let you know after I commit.

**Comment by kumar-dhanagopal** [comment]
@mickeyboxell , @romain-grecourt - I've completed my review and edits.

Here's a summary of the changes:

1. Removed the "native user only" restriction for generating the auth token.
2. Replaced the regions list with an example and a pointer to the OCI docs.
3. Completed a general edit of the text.
4. Structured the content to improve the flow.
5. Introduced numbered steps that users can follow along easily.
6. Under "Push Your Image to OCIR", added a step to find out the image path from the web console. Pls verify.
7. Under "Deploy the Image to Kubernetes", added a step for constructing the app URL. Pls verify.

**Comment by kumar-dhanagopal** [comment]
@mickeyboxell - Pls do review & confirm the changes 6 and 7 in my list above.

**Comment by mickeyboxell** [comment]
Just finished checking - 6 and 7 look good to me.

**Comment by kumar-dhanagopal** [comment]
Thank you!

**Pull request merged**
