### PR TITLE
Make SE and MP share config env var mapping

### PR DESCRIPTION
**Pull request by batsatt**
Introduces mapping for hyphenated properties.

### CODE REVIEW

**Comment by batsatt** [comment]
Fixes #446.
See related #507.

**Comment by tjquinno** [comment]
@tomas-langer I find that Diff Settings -> Hide Whitespace Changes helps to filter many formatting changes out which simplifies reviewing the substantive changes. Obviously it will not suppress _all_ types of formatting changes but it helps a lot.

**Comment by batsatt** [comment]
@tomas-langer I hear you on the whitespace, but... do we not want to be more consistent with it? In this case, the primary change is aligning chained method calls on the dot; everyone here in the US agreed that we should do so, but you may disagree.

We really need to have a more complete checkstyle and associated IDE style settings.

**Comment by batsatt** [comment]
@tjquinno The `_dash_` mapping is just a way to support any hyphenated key like`a-b`, not specifically about supporting both `a-b` and `a.b`. You're right though, that together with the other mappings both are supported.

**Comment by batsatt** [comment]
@tomas-langer Indent changes reverted.

**Comment by batsatt** [comment]
@tjquinno Also, you are correct that there is a risk, hopefully very small, that a user both actually has a config key containing the `"_dash_"` substring and wants to set it in an environment variable.

I did think about adding a mechanism to disable this mapping for that case (e.g. a `"HELIDON_DASH_MAPPING"` env var that can be set to `false`, or maybe some meta config), but it struck me as a step too far. I could easily be convinced to add it though...

**Comment by tjquinno** [comment]
My opinion is that adding a way to disable that mapping is indeed going too far. Going further down the path of "configuration which controls how configuration works" feels to me too close to an Escher art print!

**Comment by tomas-langer** [comment]
Regarding the whitespace - we need to be consistent overall, or not reformat existing code at all.
What happens now is that you reformat and commit, then somebody else does a change in the same class, reformats and commits.
This is useless. 

My approach - use the same formatting (as long as you use IntelliJ, we have a codestyle xml to use). 
Never reformat existing code - only modified and only if the original formatting is bad (or you have added code that requires a line break etc.).
For those without IntelliJ this requires configuration of their IDE to follow the same rules (unfortunately not everything gets caught by checkstyle).

**Comment by batsatt** [comment]
Yes, I believe we need both a more thorough checkstyle _and_ a matching IntelliJ codestyle xml,  preferably maintained in the source tree. This would all be easier if we could convince everyone to switch to IntelliJ; maybe we should start there ;)

**Pull request merged**
