### PR TITLE
Update surefire and failsafe to 3.0.0-M5

### PR DESCRIPTION
**Pull request by romain-grecourt**
Update surefire and failsafe to 3.0.0-M5
Remove dependencies on jupiter-engine, and junit-platform-surefire-provider

### CODE REVIEW

**Review by tomas-langer — APPROVED** [review]
LGTM

**Review by barchetta — APPROVED** [review]

**Comment by ranjankhanna** [comment]
Which release version contains this fix?

**Comment by barchetta** [comment]
@ranjankhanna it will be in 2.1.0 which should be released in the next month or so.

**Comment by ranjankhanna** [comment]
@barchetta Do you have any tentative dates? if it is going to sometime early next month, we can wait and need not to do workaround mentioned.

**Comment by barchetta** [comment]
We'd like to release early next month, but we have some dependencies that we don't fully control. So I can't fully commit to that.

**Comment by ranjankhanna** [comment]
Hello, 

Do you have any updates on 2.1.0 release?

**Comment by barchetta** [comment]
> Do you have any updates on 2.1.0 release?

Likely within a week or so.

**Pull request merged**
