### PR TITLE
Fix Typo /examples/README.md

### PR DESCRIPTION
**Pull request by emecas**

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@emecas You will to sign the OCA for us to accept your contribution. See https://www.oracle.com/technetwork/community/oca-486395.html

**Comment by emecas** [comment]
> @emecas You will to sign the OCA for us to accept your contribution. See https://www.oracle.com/technetwork/community/oca-486395.html
@romain-grecourt  It's done!

**Comment by romain-grecourt** [comment]
Nice :) @delabassee Let me know when you've confirmed @emecas 's OCA.

**Comment by delabassee** [comment]
@romain-grecourt @emecas 's OCA is now 👍!

**Comment by romain-grecourt** [comment]
Thanks!, merged.

**Pull request merged**
