### PR TITLE
Java doc typo fixing

### PR DESCRIPTION
**Pull request by ShintaroOba**
It seemed to be a typo. 
If not, I apologize.

### CODE REVIEW

**Comment by romain-grecourt** [comment]
You need to sign the [contributor agreement](https://oca.opensource.oracle.com/) before we can accept your contribution.

**Comment by ShintaroOba** [comment]
@romain-grecourt 
I've done.
Please check my agreement.

**Comment by romain-grecourt** [comment]
Can you update the copyright header to have to year with `2018, 2022` instead of `2018, 2021` (see the pipeline errors)

**Comment by romain-grecourt** [comment]
Nevermind, I've made the update for you.

**Pull request merged**
