### PR TITLE
#2221 Fixes API reference in Metrics docs

### PR DESCRIPTION
**Pull request by ninadingole**
Fixes: #2221 

Signed-off-by: Ninad Ingole ninad.ingole@gmail.com

### CODE REVIEW

**Comment by ninadingole** [comment]
@helidonrobot ci/oca-check

**Comment by ninadingole** [comment]
@helidonrobot

**Comment by ninadingole** [comment]
can someone retrigger the checks, I forgot to add my OCA details in the comments

**Comment by romain-grecourt** [comment]
Did you submit the [OCA](https://www.oracle.com/technical-resources/oracle-contributor-agreement.html) ?

**Comment by ninadingole** [comment]
@romain-grecourt yes, you can check my name in OCA list. I forgot to add `Signed-off-by` in the comment

**Pull request merged**
