### PR TITLE
Defer datasource configuration

### PR DESCRIPTION
**Pull request by ljnelson**
Adds the ability to push data source configuration until the last possible minute to help with Graal VM.

### CODE REVIEW

**Comment by ljnelson** [comment]
In general if you run with `-Djpa.lateConfigurationBinding` and `-Djpa.dataSourceNames=test,foo,bar`, then beans will be set up eagerly anticipating that at some point in the future configuration will be available for `DataSource`s named `test`, `foo` and `bar`, but that configuration will not be actually loaded until `AfterDeploymentValidation` time.

A convenient side effect of this PR is validation of data source configuration whether configuration binding is early or late.

**Comment by ljnelson** [comment]
See also: #716.

**Comment by tomas-langer** [comment]
Closing this PR as there was no progress for a long time and the originating branch is probably deleted.

**Pull request closed without merging**
