### PR TITLE
Adds META-INF/services file to native image configuration for Helidon MicroProfile CDI to resolve #2315

### LINKED ISSUE #2315: native-image failing on io.helidon.microprofile.weld.ExecutorServices
## Environment Details
* Helidon Version: 2.0.2-SNAPSHOT
* Helidon MP

----------

## Problem Description
I'm getting an exception building the native-image for the MP quickstart:

```
[INFO] 2020.09.02 01:15:12 WARNING ServiceLoader Thread[ForkJoinPool-2-worker-11,5,main]: Could not load service class io.helidon.microprofile.weld.ExecutorServices
[INFO] 2020.09.02 01:15:12 WARNING ServiceLoader Thread[ForkJoinPool-2-worker-11,5,main]: Could not load service class io.helidon.microprofile.weld.ExecutorServices
[INFO] 2020.09.02 01:15:12 WARNING ServiceLoader Thread[ForkJoinPool-2-worker-11,5,main]: Could not load service class io.helidon.microprofile.weld.ExecutorServices
[INFO] 2020.09.02 01:15:12 INFO org.jboss.weld.Bootstrap Thread[ForkJoinPool-2-worker-11,5,main]: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
[INFO] 2020.09.02 01:15:12 INFO org.jboss.weld.Event Thread[ForkJoinPool-2-worker-11,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jersey.ext.cdi1x.internal.ProcessAllAnnotatedTypes.processAnnotatedType(@Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
[INFO] 2020.09.02 01:15:12 INFO org.jboss.weld.Event Thread[ForkJoinPool-2-worker-11,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] private io.helidon.microprofile.openapi.OpenApiCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<X>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
[INFO] 2020.09.02 01:15:26 WARNING com.netflix.config.sources.URLConfigurationSource Thread[ForkJoinPool-2-worker-23,5,main]: No URLs will be polled as dynamic configuration sources.
[INFO] 2020.09.02 01:15:26 INFO com.netflix.config.sources.URLConfigurationSource Thread[ForkJoinPool-2-worker-23,5,main]: To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
[INFO] Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of rx.internal.util.unsafe.ConcurrentCircularArrayQueue. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[INFO] Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of rx.internal.util.unsafe.ConcurrentCircularArrayQueue. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[INFO] Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of rx.internal.util.unsafe.SpscUnboundedArrayQueue. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[INFO] Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of rx.internal.util.unsafe.ConcurrentSequencedCircularArrayQueue. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[INFO] Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of rx.internal.util.unsafe.ConcurrentSequencedCircularArrayQueue. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[INFO] [helidon-quickstart-mp:10965]     analysis:  25,338.59 ms,  4.41 GB
[WARNING] Error: Could not find registered service implementation class `io.helidon.microprofile.weld.ExecutorServices` for service `org.jboss.weld.bootstrap.api.Service`
[WARNING] com.oracle.svm.core.util.UserError$UserException: Could not find registered service implementation class `io.helidon.microprofile.weld.ExecutorServices` for service `org.jboss.weld.bootstrap.api.Service`
[WARNING] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[WARNING] 	at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:203)
[WARNING] 	at com.oracle.svm.hosted.ServiceLoaderFeature.duringAnalysis(ServiceLoaderFeature.java:112)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
[WARNING] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:720)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[WARNING] Error: Image build request failed with exit status 1
```
## Steps to reproduce

```
Pull the latest master and build it
cd examples/quickstarts/helidon-quickstart-mp
mvn -Dversion.plugin.helidon=2.1.1 clean package -Pnative-image
```

### PR DESCRIPTION
**Pull request by ljnelson**
Signed-off-by: Laird Nelson <laird.nelson@oracle.com>

### CODE REVIEW

**Comment by ljnelson** [comment]
@tomas-langer @barchetta One question I have (since I know zero about GraalVM native image configuration) is if I also have to do something [like this](https://github.com/cstancu/native-image-service-loader-demo/blob/master/reflection_config.json) or if that's now obsolete.

**Comment by tomas-langer** [comment]
Both `META-INF/services` and service implementations are added automatically. Let me investigate.

**Review by tomas-langer — CHANGES_REQUESTED** [review]
This is not the fix. Please close this PR.

**Comment by tomas-langer** [comment]
Fix in #2317

**Pull request closed without merging**
