### PR TITLE
 fix docker command in document

### PR DESCRIPTION
**Pull request by fastso**
fix docker command in document.

### CODE REVIEW

**Comment by romain-grecourt** [comment]
Thanks for submitting this PR.
You will to sign the OCA for us to accept your contribution. See https://www.oracle.com/technetwork/community/oca-486395.html

**Comment by fastso** [comment]
Thank you for your information.
I  Submitted the OCA procedure.

**Comment by delabassee** [comment]
@fastso please check and fill OCA's section 7.

**Comment by fastso** [comment]
@delabassee Sorry I forgot it, resend email now. Thank you !

**Comment by delabassee** [comment]
OCA is now 👍

**Pull request merged**
