### PR TITLE
WebSocket Extensions

### PR DESCRIPTION
**Pull request by dansiviter**
Few notes:
* Extensions (such as `org.glassfish.tyrus.ext.extension.deflate.PerMessageDeflateExtension`) that are in archives that are not 'bean archives' are not added as CDI ignores them. Is there a mechanism to override this or an acceptable limitation forcing workarounds? I thought about using synthetic bean archives, but the classpath would still need to be scanned to do this and not aware of any mechanism for this.
* ~The only build available with the fixes required in Tyrus is 2.0.0+ which also mandates `jakarta.websocket.*` packages which means quite a few more changes.~ No longer an issue,
* ~The both Tyrus and WebSocket API are not at release versions yet. I'm assuming this would prevent merging.~ No longer an issue.

### CODE REVIEW

**Comment by spericas** [comment]
> * The both Tyrus and WebSocket API are not at release versions yet. I'm assuming this would prevent merging.

 This is a problem. What do you think @barchetta?

**Comment by barchetta** [comment]
> > * The both Tyrus and WebSocket API are not at release versions yet. I'm assuming this would prevent merging.
> 
> This is a problem. What do you think @barchetta?

I agree that this PR should stay in WIP for now because:
1. It moves to `jakarta.websocket`. Moving to `jakarta` packages should be a coordinated decision across the project.
2. We prefer not to depend on milestone builds if at all possible.

So this PR might need to stay in the wings until we make some decisions concerning moving to Jakarta EE 9.

**Comment by romain-grecourt** [comment]
Good question. This is debatable :D ; I'd say it should be before `io.helidon`

**Comment by dansiviter** [comment]
It appears 1.17 has both the changes I submitted and still using `javax.websocket` so I've updated the MR. I guess this won't be in time for v2 release though.

**Comment by dansiviter** [comment]
Any idea how to re-trigger CI?

**Comment by dansiviter** [comment]
I'm hoping this will be merged soon but the CI never seems to trigger when I push. I tried using `/trigger` but that didn't seem to work.

**Comment by romain-grecourt** [comment]
Basically accounts that do not have access to the repository are not "trusted" and their pull requests need to  be manually triggered by "trusted" accounts.

**Comment by romain-grecourt** [comment]
you have checkstyle errors, you can run the check locally: `mvn validate -Pcheckstyle` from `./webserver/tyrus/`

**Comment by dansiviter** [comment]
Thanks @romain-grecourt for the info. I've updated the MR with the checkstyle updates.

**Review by spericas — APPROVED** [review]
LGTM

**Comment by romain-grecourt** [comment]
@dansiviter we need to do some checks for the Tyrus version change before we merge this.

**Review by barchetta — APPROVED** [review]

**Comment by barchetta** [comment]
@dansiviter thanks for the contribution and apologies this took so long to merge!

**Pull request merged**
