### PR TITLE
Added small Unit Tests to increase code coverage.

### PR DESCRIPTION
**Pull request by TheRealHaui**
Added small Unit Tests to increase code coverage.

### CODE REVIEW

**Comment by romain-grecourt** [comment]
You need to sign the OCA for us to accept your contribution, see https://www.oracle.com/technetwork/community/oca-486395.html.

**Comment by TheRealHaui** [comment]
@romain-grecourt,
I know, sent it two hours ago to the given email address.

**Comment by romain-grecourt** [comment]
Nice, thanks :) @delabassee Let me know when you've received it.

**Comment by TheRealHaui** [comment]
@romain-grecourt,
you are welcome.

**Comment by delabassee** [comment]
This OCA is now 👍

**Comment by romain-grecourt** [comment]
@tomas-langer can you review this please ?

**Pull request merged**
