### PR TITLE
Upgrade to Jersey 2.29.1

### PR DESCRIPTION
**Pull request by tomas-langer**
Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

### CODE REVIEW

**Comment by tomas-langer** [comment]
Resolves #882

**Comment by tomas-langer** [comment]
Latest version fixes:
- adds REST Client 1.3
- adds new version of hk2 with a performance bug fixed

**Comment by romain-grecourt** [comment]
The pipeline build has the following error during the open-api tck:

```
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.eclipse.microprofile.rest.client.inject.RegisterRestClient.configKey()'
	at org.glassfish.jersey.microprofile.restclient.RestClientProducer.<init>(RestClientProducer.java:108)
	at org.glassfish.jersey.microprofile.restclient.RestClientExtension.lambda$restClientRegistration$0(RestClientExtension.java:81)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.glassfish.jersey.microprofile.restclient.RestClientExtension.restClientRegistration(RestClientExtension.java:81)
```

**Comment by tomas-langer** [comment]
There are two problems
 1. wrong version of MP Rest Client (easy to fix)
 2. TCK for MP Rest Client do not pass in Helidon (need to investigate)

**Comment by tomas-langer** [comment]
The problem is in loading resources from the classpath by integration with Arquillian.
There is a resource path "/META-INF/..." - it does not work in Helidon TCK tests (would work without the leading slash).
I consider this a problem with our integration for now: will look deeper into this tomorrow

**Comment by tomas-langer** [comment]
Workaround to accept resource path starting with `/` - this works fine outside of Heildon Arquillian container, so fixed it so tests pass

**Pull request merged**
