### PR TITLE
fix in Handler : change  of () to  create()

### PR DESCRIPTION
**Pull request by Daniel-Dos**
small fix in Json doc that changed when launching version 0.11.0

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@Daniel-Dos You will to sign the OCA for us to accept your contribution. See https://www.oracle.com/technetwork/community/oca-486395.html

**Comment by Daniel-Dos** [comment]
Hi @romain-grecourt 

I already uploaded OCA on the same day as PR .

thanks .

**Comment by romain-grecourt** [comment]
@delabassee Can you confirm @Daniel-Dos 's OCA ? thanks.

**Comment by delabassee** [comment]
@romain-grecourt Yes @Daniel-Dos's OCA has been approved!

**Comment by Daniel-Dos** [comment]
thanks

**Pull request merged**
