### PR TITLE
Fault Tolerance doesn't work for Rest Client (#1121)

### PR DESCRIPTION
**Pull request by pa314159**

### CODE REVIEW

**Comment by spericas** [comment]
@pa314159 Thanks, I'll take a closer look. Could you please take a look at this page and sign the contributor agreement? 

https://github.com/oracle/helidon/blob/master/CONTRIBUTING.md

**Comment by spericas** [comment]
@pa314159 Will you consider signing the agreement?

**Comment by pa314159** [comment]
@spericas I just sent it...

**Comment by spericas** [comment]
@pa314159 Excellent, I should be finishing the review and the merge shortly. Thank you very for your contribution.

**Pull request merged**
