### PR TITLE
Gathering all resources from CDI when application is not defined.

### LINKED ISSUE #363: MP server CDI extension might discard non-ApplicationScoped root resource classes
See:

https://github.com/oracle/helidon/blob/5edc48edb60a3eb3f6402984533d4633029c82bc/microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java#L47

I believe that will rule out otherwise valid `Application`-less root resource classes, right?

Consider a root resource class annotated with `@RequestScoped`, not `@ApplicationScoped`.  It should be picked up, right?  But because it doesn't have `@ApplicationScoped` on it, this extension will ignore it.

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #363 

Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

### CODE REVIEW

**Comment by tomas-langer** [comment]
This pull requests should add the resources to synthetic application as expected. 
I have also added integration tests (not run by default - use "itg-tests" profile) that tests the possible combinations:

- There is an `@ApplicationScoped` Application class; resources are not annotated with bean defining annotation
- There is Application class that is not annotated (and is ignored), there are resources and a provider in `@RequestScoped` and `@ApplicationScoped` scopes and all are  picked up
- There is a combination of annotated Application and resource classes - only the application is used

**Comment by romain-grecourt** [comment]
The PR needs to be rebased from master to pickup the fix for the copyright check.
@tomas-langer Is this supposed to go in for 1.0 ?

**Comment by tomas-langer** [comment]
@romain-grecourt I leave that to Santiago & Laird. You can pick my work up if you like it and do the rebase (and possibly merge).
Unfortunately I leave for vacation tomorrow

**Comment by spericas** [comment]
After discussing this with @ljnelson, we agreed that the corresponding issue needs a more detailed analysis and that this PR may no cover all cases correctly. Discussion will be postpone until after 1.0.

**Pull request closed without merging**
