### PR TITLE
remove unused examples

### PR DESCRIPTION
**Pull request by wojtask9**
Not sure what it is. Probably some leftovers ?

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@tjquinno Can you take a look ?

**Comment by romain-grecourt** [comment]
I was asking you to review the changes :D, I'll retry the pipeline.

**Comment by romain-grecourt** [comment]
same error as #345, @wojtask9 can you refresh your branch with the latest master ? this should clear out the pipeline errors.

**Comment by wojtask9** [comment]
@romain-grecourt done

**Comment by delabassee** [comment]
For the record, @wojtask9 OCA has been approved.

**Comment by romain-grecourt** [comment]
I'll try to merge this PR manually and resolve the conflicts.

**Pull request merged**
