### PR TITLE
Graal 21.0.0 & musl

### PR DESCRIPTION
**Pull request by dansiviter**

### CODE REVIEW

**Comment by romain-grecourt** [comment]
FYI, there are a few things not working with GraalVM 21.0 ; not sure we can adopt that yet. CC @tomas-langer.

**Comment by dansiviter** [comment]
Happy to bounce it back to 20.3.1 if 21.0 is an issue?

**Comment by romain-grecourt** [comment]
IIRC 20.3.1 also has issues.  I think this PR is fine as it is, we will merge it when we can uptake a newer GraalVM version.

**Comment by tomas-langer** [comment]
We will use 21.0.0, please keep as is. I have added notes the the issue #2683

**Comment by tomas-langer** [comment]
Hello @dansiviter I have included this commit in my overall PR for GraalVM 21.0.0. I will reference it as soon as I push it.

**Comment by tomas-langer** [comment]
Obsolete by #2710  - new PR contains commit from this PR.

**Pull request closed without merging**
