### PR TITLE
Update Helidon GraphQL To Support java.util.Date

### PR DESCRIPTION
**Pull request by tmiddlet2666**

### CODE REVIEW

**Review by tomas-langer — CHANGES_REQUESTED** [review]
This PR cannot be merged until a release is available.

**Comment by tomas-langer** [comment]
Hello @tmiddlet2666 , I have converted this PR to a draft, as we need to wait for a release. We cannot use release candidates.

**Comment by tmiddlet2666** [comment]
Due to delay on 1.1. spec i am splitting out the changes for 1.1 from the date changes.
I will submit a new PR when the spec eventually changes.

**Review by tomas-langer — APPROVED** [review]
LGTM

**Pull request merged**
