### PR TITLE
WIP: First crack at Consul support

### PR DESCRIPTION
**Pull request by ljnelson**
Signed-off-by: Laird Nelson <laird.nelson@oracle.com>

Partially addresses #404 and #420.  (Requires PLS approval.)

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@barchetta Do we the PLS green light for this ?

**Comment by ljnelson** [comment]
Yep; noted in the PR description.

**Comment by gcameo** [comment]
I am happy to help test it out but couldn't find the repository where the pull request is coming from

**Comment by ljnelson** [comment]
FYI the branch is here (also present in the PR metadata above): https://github.com/ljnelson/helidon/tree/consul-support?files=1  You’re welcome to play with it but I’m sure it’s not ready for prime time yet.

**Comment by romain-grecourt** [comment]
This has been opened for too long, will re-open if needed when we get back to this.

**Pull request closed without merging**
