### PR TITLE
remove reference to 'this' builder in every AbstractConfig subclass

### PR DESCRIPTION
**Pull request by wojtask9**
also fix some missing generics in InMemoryConfigSource and UrlConfigSource

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@wojtask9 You will to sign the OCA for us to accept your contribution. See https://www.oracle.com/technetwork/community/oca-486395.html

**Comment by wojtask9** [comment]
@romain-grecourt I will do. But currently I'm a little bit busy :/

**Comment by wojtask9** [comment]
@romain-grecourt all this build failures looks like are not related to this change

**Comment by romain-grecourt** [comment]
@wojtask9 yes that's correct. Let us know when you signed the OCA and we'll merge this PR.

**Comment by wojtask9** [comment]
@romain-grecourt 
Yes. I sent email with filled scan of OCA.

**Comment by romain-grecourt** [comment]
Nice. @delabassee Can you let me know when you've received @wojtask9 's OCA ? Thanks.

**Pull request merged**
